# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(287, 381)
        Form.setAutoFillBackground(False)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 350, 99, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 180, 31, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 251, 31))
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 30, 91, 21))
        self.label.setObjectName("label")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit.setGeometry(QtCore.QRect(90, 30, 194, 27))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(0, 90, 151, 21))
        self.label_4.setObjectName("label_4")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(150, 90, 117, 22))
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(150, 120, 117, 22))
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup_2.addButton(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setEnabled(True)
        self.radioButton_3.setGeometry(QtCore.QRect(150, 150, 117, 22))
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup_2.addButton(self.radioButton_3)
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit_3.setGeometry(QtCore.QRect(90, 60, 194, 27))
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 91, 21))
        self.label_3.setObjectName("label_3")
        self.dateTimeEdit_4 = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit_4.setGeometry(QtCore.QRect(90, 230, 194, 27))
        self.dateTimeEdit_4.setObjectName("dateTimeEdit_4")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(90, 200, 194, 27))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 200, 91, 21))
        self.label_2.setObjectName("label_2")
        self.radioButton_4 = QtWidgets.QRadioButton(Form)
        self.radioButton_4.setEnabled(True)
        self.radioButton_4.setGeometry(QtCore.QRect(150, 320, 117, 22))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(Form)
        self.radioButton_5.setGeometry(QtCore.QRect(150, 290, 117, 22))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(Form)
        self.radioButton_6.setGeometry(QtCore.QRect(150, 260, 117, 22))
        self.radioButton_6.setObjectName("radioButton_6")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(0, 260, 151, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(0, 230, 91, 21))
        self.label_6.setObjectName("label_6")
        self.dateTimeEdit.setDisplayFormat('dd.MM.yyyy hh:mm')
        self.dateTimeEdit_2.setDisplayFormat('dd.MM.yyyy hh:mm')
        self.dateTimeEdit_3.setDisplayFormat('dd.MM.yyyy hh:mm')
        self.dateTimeEdit_4.setDisplayFormat('dd.MM.yyyy hh:mm')

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Расписание"))
        self.pushButton.setText(_translate("Form", "Установить"))
        self.pushButton_2.setText(_translate("Form", "+"))
        self.label_7.setText(_translate("Form", "Format: day.month.year hour:min"))
        self.label.setText(_translate("Form", "Включить :"))
        self.label_4.setText(_translate("Form", "Повторять каждый :"))
        self.radioButton.setText(_translate("Form", "день"))
        self.radioButton_2.setText(_translate("Form", "месяц"))
        self.radioButton_3.setText(_translate("Form", "год"))
        self.label_3.setText(_translate("Form", "Отключить:"))
        self.label_2.setText(_translate("Form", "Включить :"))
        self.radioButton_4.setText(_translate("Form", "год"))
        self.radioButton_5.setText(_translate("Form", "месяц"))
        self.radioButton_6.setText(_translate("Form", "день"))
        self.label_5.setText(_translate("Form", "Повторять каждый :"))
        self.label_6.setText(_translate("Form", "Отключить:"))




